# -*- coding: utf-8 -*-
"""Encrptix(Credit Card Fruad Detection).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prd8zWur1t3hBoo5XjZrfgamqP4bPQxr
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("C:/Users/prolo/OneDrive/Desktop/Encryptic Internship/fraudTrain.csv")
df.columns

df.isnull().sum()

df.drop(columns=['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'first', 'last', 'street', 'city', 'state', 'zip', 'trans_num', 'unix_time', 'dob'], inplace=True)

df.columns

df.head()

df = pd.get_dummies(df, columns=['merchant', 'category', 'gender', 'job'])

scaler = StandardScaler()
df['amt'] = scaler.fit_transform(df['amt'].values.reshape(-1,1))

X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

